application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 2345
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "email_url_base"
  sender_email: "email_base"
  authorization_token: "token_base"